export default {
  'ammo': { 'format': 'int', },
  'boot': { 'format': 'int', 'unit': 'secs' },
  'brokenregen': { 'format': 'round1', 'unit': 'ps' },
  'burst': { 'format': 'int' },
  'burstrof': { 'format': 'round1', 'unit': 'ps' },
  'causres': { 'format': 'pct' },
  'clip': { 'format': 'int' },
  'damage': { 'format': 'round' },
  'dps': { 'format': 'round', 'units': 'ps', 'synthetic': 'getDps' },
  'dpe': { 'format': 'round', 'units': 'ps', 'synthetic': 'getDpe' },
  'distdraw': { 'format': 'round', 'unit': 'MW' },
  'duration': { 'format': 'round1', 'unit': 's' },
  'eff': { 'format': 'round2' },
  'engcap': { 'format': 'round1', 'unit': 'MJ' },
  'engrate': { 'format': 'round1', 'unit': 'MW' },
  'eps': { 'format': 'round', 'units': 'ps', 'synthetic': 'getEps' },
  'explres': { 'format': 'pct' },
  'facinglimit': { 'format': 'round1', 'unit': 'ang' },
  'falloff': { 'format': 'round1', 'unit': 'm' },
  'fallofffromrange': { 'format': 'round1', 'unit': 'm', 'synthetic': 'getFalloff' },
  'hps': { 'format': 'round', 'units': 'ps', 'synthetic': 'getHps' },
  'hullboost': { 'format': 'pct1' },
  'hullreinforcement': { 'format': 'int' },
  'integrity': { 'format': 'round1' },
  'jitter': { 'format': 'round', 'unit': 'ang' },
  'kinres': { 'format': 'pct' },
  'mass': { 'format': 'round1', 'unit': 'T' },
  'maxfuel': { 'format': 'round1', 'unit': 'T' },
  'optmass': { 'format': 'int', 'unit': 'T' },
  'optmul': { 'format': 'pct' },
  'pgen': { 'format': 'round1', 'unit': 'MW' },
  'piercing': { 'format': 'int' },
  'power': { 'format': 'round', 'unit': 'MW' },
  'protection': { 'format': 'pct' },
  'range': { 'format': 'round1', 'unit': 'm' },
  'ranget': { 'format': 'round1', 'unit': 's' },
  'regen': { 'format': 'round1', 'unit': 'ps' },
  'reload': { 'format': 'int', 'unit': 's' },
  'rof': { 'format': 'round1', 'unit': 'ps' },
  'angle': { 'format': 'round1', 'unit': 'ang' },
  'scanrate': { 'format': 'int' },
  'scantime': { 'format': 'round1', 'unit': 's' },
  'sdps': { 'format': 'round1', 'units': 'ps', 'synthetic': 'getSDps' },
  'shield': { 'format': 'int', 'unit': 'MJ' },
  'shieldaddition': { 'format': 'round1', 'unit': 'MJ' },
  'shieldboost': { 'format': 'pct1' },
  'shieldreinforcement': { 'format': 'round1', 'unit': 'MJ' },
  'shotspeed': { 'format': 'int', 'unit': 'm/s' },
  'spinup': { 'format': 'round1', 'unit': 's' },
  'syscap': { 'format': 'round1', 'unit': 'MJ' },
  'sysrate': { 'format': 'round1', 'unit': 'MW' },
  'thermload': { 'format': 'round1' },
  'thermres': { 'format': 'pct' },
  'wepcap': { 'format': 'round1', 'unit': 'MJ' },
  'weprate': { 'format': 'round1', 'unit': 'MW' },
  'jumpboost': { 'format': 'round1', 'unit': 'LY' }
};
